# Generated by Django 5.0.1 on 2024-01-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='born_date',
            field=models.DateField(),
        ),
    ]
